<span style="color:gray">Интеллектуальный анализ данных в R и Python. Семинар 2</span>

### Работа с данными в Python. Numpy и Scipy

---

Ниже приведено описание возможностей библиотек <font color='blue'>Numpy</font> и <font color='blue'>Scipy</font> для подготовки, обработки и анализа данных.

##### 1. Numpy

<img src="numpy.PDF" width="800">

##### 2. Scipy

<img src="scipy.PDF" width="800">

<font color='green'>Задание для самостоятельной работы:</font>
    
1. Создать ячейку в данном Jupyter Notebook и повторить операции, приведенные в них разделах 1 и 2 выше.  
1. Загрузить результирующий .ipynb файл в папку /assignments/. Файлы должны именоваться как:<br>
   *'Seminar_2_' + surname*.

---

<font color='gray'>Дополнительные ссылки:</font>
* 100 NumPy exrcises: [https://github.com/rougier/numpy-100](https://github.com/rougier/numpy-100)
* CS231n Python NumPy Tutorial: [http://cs231n.github.io/python-numpy-tutorial/](http://cs231n.github.io/python-numpy-tutorial/)
* SDSS 2016 - Day 1: [https://github.com/SSDS2016/Day-1](https://github.com/SSDS2016/Day-1)
* Python Data Science Handbook, [https://github.com/jakevdp/PythonDataScienceHandbook]( https://github.com/jakevdp/PythonDataScienceHandbook)

In [1]:
import numpy as np

## Creating Arrays

In [4]:
>>> arr0 = np.array([0,11,222])
>>> arr1 = np.array([(3.665,255,11.55), (2.5,5,3)], dtype = float)
>>> arr2 = np.array([[(1.2,5,2), (3.555,6,1)], [(4,2,1), (4,5,6)]],
dtype = float)

## Initial Placeholders

In [5]:
>>> np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
>>> np.ones((3,5,2),dtype=np.int8)

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]], dtype=int8)

In [7]:
>>> arr3 = np.arange(10,9,5)

In [8]:
>>> np.linspace(0,5,11)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [9]:
>>> arr4 = np.full((2,2),7)

In [10]:
>>> arr5 = np.eye(2)

In [11]:
>>> np.random.random((3,2))

array([[0.91182915, 0.81909814],
       [0.09904155, 0.15183107],
       [0.7149284 , 0.25170485]])

In [12]:
>>> np.empty((4,2))

array([[0.00000000e+000, 0.00000000e+000],
       [2.41907520e-312, 2.44029516e-312],
       [8.48798317e-313, 9.33678148e-313],
       [8.70018275e-313, 6.90497430e-310]])

## I/O

In [18]:
>>> np.save('arrfile1', arr1)
>>> np.savez('arrfile.npz', arr1, arr2)
>>> np.load('arrfile.npz')

In [19]:
>>> np.loadtxt("file.txt")
>>> np.genfromtxt("file.csv", delimiter=',')
>>> np.savetxt("array.txt", arr1, delimiter=" ")

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: loadtxt: Empty input file: "file.txt"
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: UserWarning: genfromtxt: Empty input file: "file.csv"
  


## Data Types

In [20]:
>>> np.int64

numpy.int64

In [21]:
>>> np.float32

numpy.float32

In [22]:
>>> np.complex

complex

In [23]:
>>> np.bool

bool

In [24]:
>>> np.object

object

In [25]:
>>> np.string_

numpy.bytes_

In [26]:
>>> np.unicode_

numpy.str_

## Inspecting Your Array

In [27]:
>>> arr1.shape

(2, 3)

In [28]:
>>> len(arr1)

2

In [29]:
>>> arr2.ndim

3

In [31]:
>>> arr2.size

12

In [32]:
>>> arr3.dtype

dtype('int64')

In [33]:
>>> arr3.dtype.name

'int64'

In [34]:
>>> arr2.astype(int)

array([[[1, 5, 2],
        [3, 6, 1]],

       [[4, 2, 1],
        [4, 5, 6]]])

## Asking For Help

In [35]:
>>> np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


## Array Mathematics

In [37]:
>>> arr4 = arr1 - arr2

In [38]:
arr4

array([[[  2.465, 250.   ,   9.55 ],
        [ -1.055,  -1.   ,   2.   ]],

       [[ -0.335, 253.   ,  10.55 ],
        [ -1.5  ,   0.   ,  -3.   ]]])

In [39]:
>>> np.subtract(arr1,arr2)
>>> arr1 + arr2

array([[[  4.865, 260.   ,  13.55 ],
        [  6.055,  11.   ,   4.   ]],

       [[  7.665, 257.   ,  12.55 ],
        [  6.5  ,  10.   ,   9.   ]]])

In [40]:
>>> np.add(arr1,arr2)
>>> arr1 / arr2

array([[[  3.05416667,  51.        ,   5.775     ],
        [  0.70323488,   0.83333333,   3.        ]],

       [[  0.91625   , 127.5       ,  11.55      ],
        [  0.625     ,   1.        ,   0.5       ]]])

In [32]:
>>> np.divide(a,b)
>>> a * b

array([[ 4.8,  4. ,  3. ],
       [27. , 10. ,  8. ]])

In [41]:
>>> np.multiply(arr1,arr2)

array([[[   4.398 , 1275.    ,   23.1   ],
        [   8.8875,   30.    ,    3.    ]],

       [[  14.66  ,  510.    ,   11.55  ],
        [  10.    ,   25.    ,   18.    ]]])

In [42]:
>>> np.exp(arr1)

array([[3.90561362e+001, 5.56023165e+110, 1.03777037e+005],
       [1.21824940e+001, 1.48413159e+002, 2.00855369e+001]])

In [43]:
>>> np.sqrt(arr2)

array([[[1.09544512, 2.23606798, 1.41421356],
        [1.88547076, 2.44948974, 1.        ]],

       [[2.        , 1.41421356, 1.        ],
        [2.        , 2.23606798, 2.44948974]]])

In [44]:
>>> np.sin(arr3)

array([], dtype=float64)

In [45]:
>>> np.cos(arr2)

array([[[ 0.36235775,  0.28366219, -0.41614684],
        [-0.9157573 ,  0.96017029,  0.54030231]],

       [[-0.65364362, -0.41614684,  0.54030231],
        [-0.65364362,  0.28366219,  0.96017029]]])

In [38]:
>>> np.log(a)

array([1.09861229, 0.69314718, 0.        ])

In [60]:
>>> arr1.dot(arr2)

ValueError: shapes (2,3) and (2,2,3) not aligned: 3 (dim 1) != 2 (dim 1)

In [61]:
>>> arr1 == arr2

array([[[False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False,  True, False]]])

In [62]:
>>> arr2 < 2

array([[[ True, False, False],
        [False, False,  True]],

       [[False, False,  True],
        [False, False, False]]])

In [63]:
>>> np.array_equal(arr1, arr2)

False

In [43]:
>>> arr2.sum()

6

In [44]:
>>> arr1.min()

1

In [64]:
>>> arr2.max(axis=0)

array([[4., 5., 2.],
       [4., 6., 6.]])

In [65]:
>>> arr1.cumsum(axis=1)

array([[  3.665, 258.665, 270.215],
       [  2.5  ,   7.5  ,  10.5  ]])

In [66]:
>>> arr2.mean()

3.3962499999999998

In [67]:
np.median(arr2)

3.7775

In [68]:
>>> np.corrcoef(arr1)

array([[1.      , 0.986821],
       [0.986821, 1.      ]])

In [69]:

>>> np.std(arr1)

93.16526491566239

In [70]:
>>> h = arr1.view()
>>> h

array([[  3.665, 255.   ,  11.55 ],
       [  2.5  ,   5.   ,   3.   ]])

In [71]:
>>> np.copy(arr2)

array([[[1.2  , 5.   , 2.   ],
        [3.555, 6.   , 1.   ]],

       [[4.   , 2.   , 1.   ],
        [4.   , 5.   , 6.   ]]])

In [74]:
>>> arr4 = arr1.copy()
>>> arr4

array([[  3.665, 255.   ,  11.55 ],
       [  2.5  ,   5.   ,   3.   ]])

In [75]:
>>> arr4.sort()
>>> arr4

array([[  3.665,  11.55 , 255.   ],
       [  2.5  ,   3.   ,   5.   ]])

In [76]:
>>> arr4.sort(axis=0)
>>> arr4

array([[  2.5  ,   3.   ,   5.   ],
       [  3.665,  11.55 , 255.   ]])

## Subsetting, Slicing, Indexing

In [81]:
>>> arr2[1]

array([[4., 2., 1.],
       [4., 5., 6.]])

In [84]:
>>> arr2[1,1,2] 

6.0

In [85]:
>>> arr1[0:2]

array([[  3.665, 255.   ,  11.55 ],
       [  2.5  ,   5.   ,   3.   ]])

In [86]:
>>> arr2[0:2,1]

array([[3.555, 6.   , 1.   ],
       [4.   , 5.   , 6.   ]])

In [87]:
>>> arr4[:1] 

array([[2.5, 3. , 5. ]])

In [88]:
>>> arr4[1,...] 

array([  3.665,  11.55 , 255.   ])

In [89]:
>>> arr4[ : :-1] 

array([[  3.665,  11.55 , 255.   ],
       [  2.5  ,   3.   ,   5.   ]])

In [90]:
>>> arr4[arr4<2] 

array([], dtype=float64)

In [92]:
>>> arr2[[1, 0, 1, 0],[0, 1, 1, 0]]

array([[4.   , 2.   , 1.   ],
       [3.555, 6.   , 1.   ],
       [4.   , 5.   , 6.   ],
       [1.2  , 5.   , 2.   ]])

In [94]:
>>> arr2[[1, 0, 1, 0]][:,[0,1,1,0]] 

array([[[4.   , 2.   , 1.   ],
        [4.   , 5.   , 6.   ],
        [4.   , 5.   , 6.   ],
        [4.   , 2.   , 1.   ]],

       [[1.2  , 5.   , 2.   ],
        [3.555, 6.   , 1.   ],
        [3.555, 6.   , 1.   ],
        [1.2  , 5.   , 2.   ]],

       [[4.   , 2.   , 1.   ],
        [4.   , 5.   , 6.   ],
        [4.   , 5.   , 6.   ],
        [4.   , 2.   , 1.   ]],

       [[1.2  , 5.   , 2.   ],
        [3.555, 6.   , 1.   ],
        [3.555, 6.   , 1.   ],
        [1.2  , 5.   , 2.   ]]])

## Array Manipulation

In [95]:
>>> i = np.transpose(arr2)
>>> i.T 

array([[[1.2  , 5.   , 2.   ],
        [3.555, 6.   , 1.   ]],

       [[4.   , 2.   , 1.   ],
        [4.   , 5.   , 6.   ]]])

In [96]:
>>> arr4.ravel() 

array([  2.5  ,   3.   ,   5.   ,   3.665,  11.55 , 255.   ])

In [97]:
>>> arr4.reshape(3,-2)

array([[  2.5  ,   3.   ],
       [  5.   ,   3.665],
       [ 11.55 , 255.   ]])

In [98]:
>>> np.resize(arr4,(2,6))

array([[  2.5  ,   3.   ,   5.   ,   3.665,  11.55 , 255.   ],
       [  2.5  ,   3.   ,   5.   ,   3.665,  11.55 , 255.   ]])

In [99]:
>>> np.append(arr3,arr4)

array([  2.5  ,   3.   ,   5.   ,   3.665,  11.55 , 255.   ])

In [100]:
>>> np.insert(arr1, 1, 5) 

array([  3.665,   5.   , 255.   ,  11.55 ,   2.5  ,   5.   ,   3.   ])

In [101]:
>>> np.delete(arr1,[1]) 

array([ 3.665, 11.55 ,  2.5  ,  5.   ,  3.   ])

In [102]:
>>> np.concatenate((arr1,arr4),axis=0)

array([[  3.665, 255.   ,  11.55 ],
       [  2.5  ,   5.   ,   3.   ],
       [  2.5  ,   3.   ,   5.   ],
       [  3.665,  11.55 , 255.   ]])

In [104]:
>>> np.vstack((arr1,arr4))

array([[  3.665, 255.   ,  11.55 ],
       [  2.5  ,   5.   ,   3.   ],
       [  2.5  ,   3.   ,   5.   ],
       [  3.665,  11.55 , 255.   ]])

In [105]:
>>> np.r_[arr4,arr1] 

array([[  2.5  ,   3.   ,   5.   ],
       [  3.665,  11.55 , 255.   ],
       [  3.665, 255.   ,  11.55 ],
       [  2.5  ,   5.   ,   3.   ]])

In [108]:
>>> np.hstack((arr1,arr4)) 

array([[  3.665, 255.   ,  11.55 ,   2.5  ,   3.   ,   5.   ],
       [  2.5  ,   5.   ,   3.   ,   3.665,  11.55 , 255.   ]])

In [109]:
>>> np.column_stack((arr1,arr4))

array([[  3.665, 255.   ,  11.55 ,   2.5  ,   3.   ,   5.   ],
       [  2.5  ,   5.   ,   3.   ,   3.665,  11.55 , 255.   ]])

In [110]:
>>> np.c_[arr1,arr4] 

array([[  3.665, 255.   ,  11.55 ,   2.5  ,   3.   ,   5.   ],
       [  2.5  ,   5.   ,   3.   ,   3.665,  11.55 , 255.   ]])

In [111]:
>>> np.hsplit(arr1,3) 

[array([[3.665],
        [2.5  ]]), array([[255.],
        [  5.]]), array([[11.55],
        [ 3.  ]])]

In [112]:
>>> np.vsplit(arr4,2) 

[array([[2.5, 3. , 5. ]]), array([[  3.665,  11.55 , 255.   ]])]

In [113]:
>>> import numpy as np
>>> a = np.array([11,22,33])
>>> b = np.array([(1+3j,6j,3j), (5j,6j,8j)])
>>> c = np.array([[(1.8,7,4), (9,3,2)], [(2,44.4,22), (7,3,2)]])

In [114]:
>>> a

array([11, 22, 33])

In [115]:
>>> b

array([[1.+3.j, 0.+6.j, 0.+3.j],
       [0.+5.j, 0.+6.j, 0.+8.j]])

In [116]:
>>> c

array([[[ 1.8,  7. ,  4. ],
        [ 9. ,  3. ,  2. ]],

       [[ 2. , 44.4, 22. ],
        [ 7. ,  3. ,  2. ]]])

In [117]:
>>> np.mgrid[0:5,0:5] 

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [118]:
>>> np.ogrid[0:2,0:2]

[array([[0],
        [1]]), array([[0, 1]])]

In [119]:
>>> np.r_[3,[0]*5,-1:1:10j]

array([ 3.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        , -1.        , -0.77777778, -0.55555556, -0.33333333,
       -0.11111111,  0.11111111,  0.33333333,  0.55555556,  0.77777778,
        1.        ])

In [120]:
>>> b1 = np.array([(1.5,2,3), (4,5,6)], dtype = float)
>>> np.c_[b,b1]

array([[1. +3.j, 0. +6.j, 0. +3.j, 1.5+0.j, 2. +0.j, 3. +0.j],
       [0. +5.j, 0. +6.j, 0. +8.j, 4. +0.j, 5. +0.j, 6. +0.j]])

In [121]:
>>> np.transpose(b)

array([[1.+3.j, 0.+5.j],
       [0.+6.j, 0.+6.j],
       [0.+3.j, 0.+8.j]])

In [122]:
>>> b.flatten()

array([1.+3.j, 0.+6.j, 0.+3.j, 0.+5.j, 0.+6.j, 0.+8.j])

In [123]:
>>> np.hstack((b,b1))

array([[1. +3.j, 0. +6.j, 0. +3.j, 1.5+0.j, 2. +0.j, 3. +0.j],
       [0. +5.j, 0. +6.j, 0. +8.j, 4. +0.j, 5. +0.j, 6. +0.j]])

In [124]:
>>> np.vstack((a,b))

array([[11.+0.j, 22.+0.j, 33.+0.j],
       [ 1.+3.j,  0.+6.j,  0.+3.j],
       [ 0.+5.j,  0.+6.j,  0.+8.j]])

In [125]:
>>> np.hsplit(c,2)

[array([[[ 1.8,  7. ,  4. ]],
 
        [[ 2. , 44.4, 22. ]]]), array([[[9., 3., 2.]],
 
        [[7., 3., 2.]]])]

# SciPy
## Interacting With NumPy

In [126]:
from numpy import poly1d

In [127]:
 p = poly1d([22,34,59]) 

In [128]:
p

poly1d([22, 34, 59])

In [129]:
>>> def myfunc(a): 
    if a < 50:
     return a*2
    else:
     return a/2
>>> np.vectorize(myfunc) 

In [130]:
>>> np.real(b)

array([[1., 0., 0.],
       [0., 0., 0.]])

In [131]:
 np.imag(b)

array([[3., 6., 3.],
       [5., 6., 8.]])

In [132]:
np.real_if_close(c,tol=1000)

array([[[ 1.8,  7. ,  4. ],
        [ 9. ,  3. ,  2. ]],

       [[ 2. , 44.4, 22. ],
        [ 7. ,  3. ,  2. ]]])

In [133]:
np.cast['f'](np.pi)

array(3.1415927, dtype=float32)

In [134]:
np.angle(b,deg=True)

array([[71.56505118, 90.        , 90.        ],
       [90.        , 90.        , 90.        ]])

In [135]:
>>> g = np.linspace(0,np.pi,num=5)
>>> g

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265])

In [136]:
>>> g [3:] += np.pi

In [137]:
>>> np.unwrap(g) 

array([ 0.        ,  0.78539816,  1.57079633, -0.78539816,  0.        ])

In [138]:
>>> np.logspace(0,10,3)

array([1.e+00, 1.e+05, 1.e+10])

In [139]:
>>> np.select([c<4],[c*2])

array([[[3.6, 0. , 0. ],
        [0. , 6. , 4. ]],

       [[4. , 0. , 0. ],
        [0. , 6. , 4. ]]])

In [140]:
>>> import scipy.misc as misc
>>> misc.factorial(a)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: `factorial` is deprecated!
Importing `factorial` from scipy.misc is deprecated in scipy 1.0.0. Use `scipy.special.factorial` instead.
  


array([3.99168000e+07, 1.12400073e+21, 8.68331762e+36])

In [141]:
>>> misc.comb(10,3,exact=True)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `comb` is deprecated!
Importing `comb` from scipy.misc is deprecated in scipy 1.0.0. Use `scipy.special.comb` instead.
  """Entry point for launching an IPython kernel.


120

In [142]:
>>> misc.central_diff_weights(3)

array([-0.5,  0. ,  0.5])

In [143]:
>>> misc.derivative(myfunc,1.0)

2.0

## Linear Algebra

In [144]:
>>> from scipy import linalg, sparse

In [145]:
>>> A = np.matrix(np.random.random((21,29)))
>>> B = np.asmatrix(b)
>>> C = np.mat(np.random.random((11,55)))
>>> D = np.mat([[31,42], [59,622]])

In [146]:
>>> A

matrix([[0.97132233, 0.66042726, 0.69190242, 0.71974627, 0.6094526 ,
         0.25546314, 0.58647431, 0.39292868, 0.50242821, 0.15976851,
         0.53447704, 0.0577309 , 0.47409608, 0.99231216, 0.66902347,
         0.77978097, 0.044589  , 0.93616097, 0.63775873, 0.46796494,
         0.71734346, 0.75899716, 0.94822785, 0.24159651, 0.26130943,
         0.67870186, 0.70207107, 0.1775853 , 0.99564429],
        [0.66646552, 0.60654223, 0.34943153, 0.71187759, 0.67461239,
         0.25666407, 0.57240428, 0.03011043, 0.62723807, 0.47606132,
         0.38731159, 0.08619278, 0.53929711, 0.77281005, 0.98740526,
         0.44214033, 0.54329454, 0.99344832, 0.52387192, 0.15046529,
         0.90234108, 0.11001037, 0.63958478, 0.97588397, 0.28023876,
         0.98143876, 0.54071211, 0.24824362, 0.60714678],
        [0.61994043, 0.09849086, 0.75675226, 0.3040482 , 0.87517   ,
         0.72046232, 0.29464248, 0.66345645, 0.74184338, 0.58992765,
         0.89791693, 0.90012427, 0.18770108, 0.77082896,

In [147]:
>>> B

matrix([[1.+3.j, 0.+6.j, 0.+3.j],
        [0.+5.j, 0.+6.j, 0.+8.j]])

In [148]:
>>> C

matrix([[9.69713785e-01, 7.53164726e-01, 3.16418391e-01, 8.17926561e-01,
         8.09762360e-01, 7.06861110e-01, 6.03032304e-01, 5.98646861e-01,
         6.75847126e-01, 8.21692964e-01, 7.82764220e-02, 9.63254927e-01,
         2.99447594e-01, 4.22825374e-01, 3.79196532e-01, 5.58192155e-01,
         4.31611787e-01, 3.69446579e-01, 2.36529654e-01, 4.86230521e-01,
         3.24648646e-01, 3.44085037e-01, 8.65488025e-01, 6.95271552e-01,
         5.09749188e-01, 5.25030779e-01, 1.39806048e-01, 5.41387515e-01,
         6.48818541e-01, 2.74788552e-01, 8.38550639e-01, 2.72043731e-01,
         2.08743862e-01, 1.48947507e-03, 6.49700806e-01, 1.23719572e-01,
         6.38925940e-02, 1.57569072e-01, 2.97408280e-01, 6.31132599e-01,
         6.96337743e-01, 2.49180358e-01, 2.00757415e-01, 6.01994391e-01,
         7.43648049e-01, 6.13470861e-01, 2.90808753e-01, 2.62401748e-01,
         3.62803085e-01, 7.83979191e-01, 8.44684595e-02, 9.18863667e-01,
         3.10679709e-01, 4.45872643e-02, 7.04967452

In [149]:
D

matrix([[ 31,  42],
        [ 59, 622]])

In [150]:
A.I

matrix([[ 3.17176726e-01, -2.94490068e-01, -2.28463898e-01,
          4.73375777e-01, -6.78012372e-02,  5.84007156e-02,
         -6.62524222e-02,  1.25008212e-01, -1.41801478e-02,
         -6.87893466e-02, -1.43677793e-02, -9.95543621e-02,
          1.77019828e-01, -2.15569346e-01, -2.18832730e-01,
         -9.74582479e-02,  5.61506841e-02,  6.90557036e-02,
         -7.09067507e-02, -1.16417053e-01,  3.53370088e-01],
        [ 1.37253038e-01,  2.18796526e-02, -2.15045463e-01,
          4.58712416e-03,  1.60618182e-01,  1.15311944e-01,
         -2.58366611e-01,  2.13394124e-01, -2.82874333e-01,
         -1.61761508e-01,  4.46130859e-01,  1.17607586e-01,
          2.55671312e-01, -3.07704407e-01,  2.57673688e-02,
          1.34177619e-01, -8.88985576e-02, -2.74116450e-01,
         -1.11215101e-01,  1.15546771e-01,  5.95450927e-02],
        [ 4.05951142e-01, -3.30493448e-01,  2.57331003e-02,
          5.77336352e-02, -3.92806568e-02, -2.04605001e-01,
         -2.23298943e-01,  6.06902305e

In [151]:
A.H

matrix([[0.97132233, 0.66646552, 0.61994043, 0.79731218, 0.30800721,
         0.50759889, 0.55785739, 0.58610744, 0.33476084, 0.24425543,
         0.09331303, 0.32493992, 0.77130797, 0.00857008, 0.34160691,
         0.68306828, 0.6195271 , 0.51995696, 0.47451963, 0.09528394,
         0.94064235],
        [0.66042726, 0.60654223, 0.09849086, 0.25176711, 0.92241004,
         0.59811344, 0.50829385, 0.38032598, 0.23497038, 0.15327975,
         0.7973502 , 0.46126594, 0.90360038, 0.16190273, 0.63577177,
         0.82799631, 0.51125973, 0.00566067, 0.34463026, 0.10790159,
         0.63564817],
        [0.69190242, 0.34943153, 0.75675226, 0.06460389, 0.14038282,
         0.16201787, 0.44711434, 0.47720013, 0.55784705, 0.09216115,
         0.86634786, 0.10367467, 0.6953492 , 0.6979986 , 0.157384  ,
         0.4917581 , 0.77305911, 0.71575084, 0.35703626, 0.22019219,
         0.35986877],
        [0.71974627, 0.71187759, 0.3040482 , 0.86814907, 0.09015231,
         0.31958015, 0.70636381, 0.39

In [164]:
linalg.inv(D)

array([[ 0.037015  , -0.0024994 ],
       [-0.00351107,  0.0018448 ]])

In [153]:
A.T

matrix([[0.97132233, 0.66646552, 0.61994043, 0.79731218, 0.30800721,
         0.50759889, 0.55785739, 0.58610744, 0.33476084, 0.24425543,
         0.09331303, 0.32493992, 0.77130797, 0.00857008, 0.34160691,
         0.68306828, 0.6195271 , 0.51995696, 0.47451963, 0.09528394,
         0.94064235],
        [0.66042726, 0.60654223, 0.09849086, 0.25176711, 0.92241004,
         0.59811344, 0.50829385, 0.38032598, 0.23497038, 0.15327975,
         0.7973502 , 0.46126594, 0.90360038, 0.16190273, 0.63577177,
         0.82799631, 0.51125973, 0.00566067, 0.34463026, 0.10790159,
         0.63564817],
        [0.69190242, 0.34943153, 0.75675226, 0.06460389, 0.14038282,
         0.16201787, 0.44711434, 0.47720013, 0.55784705, 0.09216115,
         0.86634786, 0.10367467, 0.6953492 , 0.6979986 , 0.157384  ,
         0.4917581 , 0.77305911, 0.71575084, 0.35703626, 0.22019219,
         0.35986877],
        [0.71974627, 0.71187759, 0.3040482 , 0.86814907, 0.09015231,
         0.31958015, 0.70636381, 0.39

In [165]:
A.H

matrix([[0.97132233, 0.66646552, 0.61994043, 0.79731218, 0.30800721,
         0.50759889, 0.55785739, 0.58610744, 0.33476084, 0.24425543,
         0.09331303, 0.32493992, 0.77130797, 0.00857008, 0.34160691,
         0.68306828, 0.6195271 , 0.51995696, 0.47451963, 0.09528394,
         0.94064235],
        [0.66042726, 0.60654223, 0.09849086, 0.25176711, 0.92241004,
         0.59811344, 0.50829385, 0.38032598, 0.23497038, 0.15327975,
         0.7973502 , 0.46126594, 0.90360038, 0.16190273, 0.63577177,
         0.82799631, 0.51125973, 0.00566067, 0.34463026, 0.10790159,
         0.63564817],
        [0.69190242, 0.34943153, 0.75675226, 0.06460389, 0.14038282,
         0.16201787, 0.44711434, 0.47720013, 0.55784705, 0.09216115,
         0.86634786, 0.10367467, 0.6953492 , 0.6979986 , 0.157384  ,
         0.4917581 , 0.77305911, 0.71575084, 0.35703626, 0.22019219,
         0.35986877],
        [0.71974627, 0.71187759, 0.3040482 , 0.86814907, 0.09015231,
         0.31958015, 0.70636381, 0.39

In [166]:
np.trace(A) 

12.837599412983309

In [167]:
linalg.norm(A)

13.921771778723167

In [168]:
linalg.norm(A,1)

12.388638566701585

In [169]:
>>> linalg.norm(A,np.inf) 

17.062255908340727

In [170]:
 np.linalg.matrix_rank(C) 

11

In [172]:
 linalg.det(D)

16804.0

In [173]:
linalg.solve(D,b)

array([[ 0.037015  +0.09854796j,  0.        +0.20709355j,
         0.        +0.09104975j],
       [-0.00351107-0.00130921j,  0.        -0.00999762j,
        -0.        +0.00422518j]])

In [174]:
>>> E = np.mat(a).T
>>> F = E
>>> E

matrix([[11],
        [22],
        [33]])

In [175]:
linalg.lstsq(F,E)

(array([[1.]]), array([0.]), 1, array([41.15823125]))

In [176]:
linalg.pinv(C) 

array([[ 0.13462402, -0.10041886, -0.04033158, -0.02937055,  0.09098364,
         0.03447364, -0.00201904,  0.0013604 ,  0.05459455, -0.10105658,
        -0.00567278],
       [ 0.08422542, -0.02230932, -0.00056337, -0.01554361,  0.00910236,
        -0.09314446, -0.09241848,  0.01694169,  0.0391473 ,  0.03789971,
         0.07287027],
       [-0.04345796,  0.02617554,  0.03980857,  0.09685686, -0.03811949,
         0.0265919 , -0.00802195, -0.06925685, -0.0698014 ,  0.01405951,
         0.05930876],
       [ 0.14115037, -0.04124787, -0.06467495,  0.07838762, -0.09694114,
        -0.0549858 , -0.07031519, -0.00297485, -0.00144676,  0.02379316,
         0.12613464],
       [ 0.03824045,  0.04809502, -0.03704903, -0.00499494,  0.05026325,
         0.00495065,  0.09255514, -0.07512726, -0.08446421, -0.04848155,
         0.05304113],
       [ 0.04047639, -0.10330321,  0.0766303 , -0.01781602, -0.07191736,
         0.01028926,  0.08910802,  0.02531986,  0.02606927,  0.01315536,
        -0.035

In [177]:
linalg.pinv2(C) 

array([[ 0.13462402, -0.10041886, -0.04033158, -0.02937055,  0.09098364,
         0.03447364, -0.00201904,  0.0013604 ,  0.05459455, -0.10105658,
        -0.00567278],
       [ 0.08422542, -0.02230932, -0.00056337, -0.01554361,  0.00910236,
        -0.09314446, -0.09241848,  0.01694169,  0.0391473 ,  0.03789971,
         0.07287027],
       [-0.04345796,  0.02617554,  0.03980857,  0.09685686, -0.03811949,
         0.0265919 , -0.00802195, -0.06925685, -0.0698014 ,  0.01405951,
         0.05930876],
       [ 0.14115037, -0.04124787, -0.06467495,  0.07838762, -0.09694114,
        -0.0549858 , -0.07031519, -0.00297485, -0.00144676,  0.02379316,
         0.12613464],
       [ 0.03824045,  0.04809502, -0.03704903, -0.00499494,  0.05026325,
         0.00495065,  0.09255514, -0.07512726, -0.08446421, -0.04848155,
         0.05304113],
       [ 0.04047639, -0.10330321,  0.0766303 , -0.01781602, -0.07191736,
         0.01028926,  0.08910802,  0.02531986,  0.02606927,  0.01315536,
        -0.035

In [178]:
>>> F = np.eye(3, k=1)
>>> F

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [179]:
>>> G = np.mat(np.identity(2))
>>> G

matrix([[1., 0.],
        [0., 1.]])

In [180]:
>>> C[C > 0.5] = 0
>>> C

matrix([[0.00000000e+00, 0.00000000e+00, 3.16418391e-01, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 7.82764220e-02, 0.00000000e+00,
         2.99447594e-01, 4.22825374e-01, 3.79196532e-01, 0.00000000e+00,
         4.31611787e-01, 3.69446579e-01, 2.36529654e-01, 4.86230521e-01,
         3.24648646e-01, 3.44085037e-01, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 1.39806048e-01, 0.00000000e+00,
         0.00000000e+00, 2.74788552e-01, 0.00000000e+00, 2.72043731e-01,
         2.08743862e-01, 1.48947507e-03, 0.00000000e+00, 1.23719572e-01,
         6.38925940e-02, 1.57569072e-01, 2.97408280e-01, 0.00000000e+00,
         0.00000000e+00, 2.49180358e-01, 2.00757415e-01, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 2.90808753e-01, 2.62401748e-01,
         3.62803085e-01, 0.00000000e+00, 8.44684595e-02, 0.00000000e+00,
         3.10679709e-01, 4.45872643e-02, 0.00000000

In [181]:
>>> H = sparse.csr_matrix(C)
>>> H

<11x55 sparse matrix of type '<class 'numpy.float64'>'
	with 308 stored elements in Compressed Sparse Row format>

In [182]:
>>> I = sparse.csc_matrix(D)
>>> I

<2x2 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements in Compressed Sparse Column format>

In [183]:
>>> J = sparse.dok_matrix(A)
>>> J

<21x29 sparse matrix of type '<class 'numpy.float64'>'
	with 609 stored elements in Dictionary Of Keys format>

In [184]:
>>> sparse.isspmatrix_csc(A)

False

In [187]:
>>> linalg.inv(D) 

array([[ 0.037015  , -0.0024994 ],
       [-0.00351107,  0.0018448 ]])

In [188]:
linalg.norm(A)

13.921771778723167

In [195]:
help(linalg) 

Help on package scipy.linalg in scipy:

NAME
    scipy.linalg

DESCRIPTION
    Linear algebra (:mod:`scipy.linalg`)
    
    .. currentmodule:: scipy.linalg
    
    Linear algebra functions.
    
    .. seealso::
    
       `numpy.linalg` for more linear algebra functions.  Note that
       although `scipy.linalg` imports most of them, identically named
       functions from `scipy.linalg` may offer more or slightly differing
       functionality.
    
    
    Basics
    
    .. autosummary::
       :toctree: generated/
    
       inv - Find the inverse of a square matrix
       solve - Solve a linear system of equations
       solve_banded - Solve a banded linear system
       solveh_banded - Solve a Hermitian or symmetric banded system
       solve_circulant - Solve a circulant system
       solve_triangular - Solve a triangular matrix
       solve_toeplitz - Solve a toeplitz matrix
       det - Find the determinant of a square matrix
       norm - Matrix and vector norm
       l

In [196]:
>>> np.info(np.matrix)

 matrix()

matrix(data, dtype=None, copy=True)

.. note:: It is no longer recommended to use this class, even for linear
          algebra. Instead use regular arrays. The class may be removed
          in the future.

Returns a matrix from an array-like object, or from a string of data.
A matrix is a specialized 2-D array that retains its 2-D nature
through operations.  It has certain special operators, such as ``*``
(matrix multiplication) and ``**`` (matrix power).

Parameters
----------
data : array_like or string
   If `data` is a string, it is interpreted as a matrix with commas
   or spaces separating columns, and semicolons separating rows.
dtype : data-type
   Data-type of the output matrix.
copy : bool
   If `data` is already an `ndarray`, then this flag determines
   whether the data is copied (the default), or whether a view is
   constructed.

See Also
--------
array

Examples
--------
>>> a = np.matrix('1 2; 3 4')
>>> print(a)
[[1 2]
 [3 4]]

>>> np.matrix([[1, 2], [3, 4]

In [200]:
np.add(C,C)

matrix([[0.00000000e+00, 0.00000000e+00, 6.32836781e-01, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 1.56552844e-01, 0.00000000e+00,
         5.98895188e-01, 8.45650747e-01, 7.58393063e-01, 0.00000000e+00,
         8.63223573e-01, 7.38893158e-01, 4.73059308e-01, 9.72461041e-01,
         6.49297293e-01, 6.88170074e-01, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 2.79612095e-01, 0.00000000e+00,
         0.00000000e+00, 5.49577105e-01, 0.00000000e+00, 5.44087463e-01,
         4.17487723e-01, 2.97895015e-03, 0.00000000e+00, 2.47439144e-01,
         1.27785188e-01, 3.15138144e-01, 5.94816560e-01, 0.00000000e+00,
         0.00000000e+00, 4.98360716e-01, 4.01514829e-01, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 5.81617505e-01, 5.24803495e-01,
         7.25606169e-01, 0.00000000e+00, 1.68936919e-01, 0.00000000e+00,
         6.21359418e-01, 8.91745286e-02, 0.00000000

In [203]:
np.subtract(C,C)

matrix([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0

In [204]:
 np.divide(B,B) 

matrix([[1.+0.j, 1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j, 1.+0.j]])

In [211]:
D @ D

matrix([[  3439,  27426],
        [ 38527, 389362]])

In [213]:
np.multiply(B,B) 

matrix([[ -8.+6.j, -36.+0.j,  -9.+0.j],
        [-25.+0.j, -36.+0.j, -64.+0.j]])

In [220]:
np.dot(D,D) 

matrix([[  3439,  27426],
        [ 38527, 389362]])

In [222]:
np.vdot(D,D)

matrix([[961]])

In [224]:
np.inner(A,A)

matrix([[11.74043665,  9.95675748,  8.78830189,  8.15380686,  6.37316622,
          8.35927392,  9.38772558,  8.39803392,  7.26954684,  6.92231879,
          7.33654188,  7.60098043,  8.15193277,  8.31655201,  9.95573881,
          7.42096765,  9.15647056,  7.78947172,  7.8502701 ,  7.69049883,
          8.31038649],
        [ 9.95675748, 10.65781645,  8.06704268,  8.08665579,  6.81947214,
          7.63353456,  8.28622898,  7.91799106,  7.42900765,  6.98586241,
          6.93448593,  7.24282544,  7.87659202,  7.81409715,  9.02974504,
          6.83433625,  8.8774247 ,  7.57137508,  6.47062182,  7.0427711 ,
          8.01985609],
        [ 8.78830189,  8.06704268, 10.68772304,  7.84319542,  6.03744482,
          7.44809382,  9.60171911,  9.05657998,  7.35501922,  6.26389369,
          7.32349004,  6.77199719,  7.48718608,  7.03886379,  7.58036532,
          7.51776887,  8.20109038,  7.72087639,  6.56735502,  7.77138689,
          7.61326075],
        [ 8.15380686,  8.08665579,  7.84319

In [225]:
np.outer(A,D)

array([[ 30.11099218,  40.7955378 ,  57.30801738, 604.16248831],
       [ 20.47324493,  27.73794474,  38.96520809, 410.78575307],
       [ 21.44897509,  29.05990173,  40.8222429 , 430.36330656],
       ...,
       [  8.9374815 ,  12.1088459 ,  17.01004543, 179.32624166],
       [ 15.08876477,  20.44284259,  28.71732649, 302.74876401],
       [ 28.159687  ,  38.15183399,  53.59424299, 565.01049392]])

In [229]:
np.tensordot(D,D)

array(393090)

In [230]:
 np.kron(A,D)

matrix([[ 30.11099218,  40.7955378 ,  20.47324493, ...,   7.45858267,
          30.86497287,  41.81706002],
        [ 57.30801738, 604.16248831,  38.96520809, ..., 110.45805759,
          58.74301288, 619.29074599],
        [ 20.6604312 ,  27.99155195,  18.80280914, ...,  10.42623213,
          18.82155032,  25.50016495],
        ...,
        [  5.62175252,  59.26661135,   6.36619405, ..., 209.20568957,
           3.57864524,  37.7274125 ],
        [ 29.15991289,  39.50697875,  19.7050934 , ...,  20.44284259,
          28.159687  ,  38.15183399],
        [ 55.49789872, 585.07954244,  37.50324227, ..., 302.74876401,
          53.59424299, 565.01049392]])

In [233]:
linalg.expm(D)

array([[6.04200145e+269, 6.09487983e+270],
       [8.56185500e+270, 8.63678664e+271]])

In [234]:
linalg.logm(D) 

array([[3.31164282, 0.22073712],
       [0.31008309, 6.41772941]])

In [235]:
linalg.sinm(D)

array([[ 0.97850082, -0.12791796],
       [-0.17969428, -0.82148763]])

In [236]:
linalg.cosm(D)

array([[-0.13542102, -0.0293629 ],
       [-0.04124788, -0.54859893]])

In [239]:
linalg.tanm(D) 

array([[-7.41756796,  0.63018578],
       [ 0.88526097,  1.4500462 ]])

In [240]:
linalg.sinhm(D)

array([[3.02100073e+269, 3.04743992e+270],
       [4.28092750e+270, 4.31839332e+271]])

In [241]:
linalg.coshm(D)

array([[3.02100073e+269, 3.04743992e+270],
       [4.28092750e+270, 4.31839332e+271]])

In [244]:
linalg.tanhm(D) 

/usr/lib/python3/dist-packages/scipy/linalg/matfuncs.py:486: LinAlgWarning: scipy.linalg.solve
Ill-conditioned matrix detected. Result is not guaranteed to be accurate.
Reciprocal condition number9.153880e-19
  return _maybe_real(A, solve(coshm(A), sinhm(A)))


array([[ 1.,  0.],
       [-0.,  1.]])

In [243]:
 linalg.signm(D)

array([[1., 0.],
       [0., 1.]])

In [246]:
 linalg.sqrtm(D)

array([[ 5.31823942,  1.3905604 ],
       [ 1.95340628, 24.8854108 ]])

In [248]:
>>> la, v = linalg.eig(D)
>>> la

array([ 26.83643865+0.j, 626.16356135+0.j])

In [250]:
linalg.funm(D, lambda x: x*x) 

array([[  3439.,  27426.],
       [ 38527., 389362.]])

In [251]:
l1, l2 = la

In [252]:
v[:,0] 

array([-0.9951223 ,  0.09864888])

In [253]:
v[:,1]

array([-0.07039377, -0.99751928])

In [255]:
linalg.eigvals(D) 

array([ 26.83643865+0.j, 626.16356135+0.j])

In [256]:
>>> U,s,Vh = linalg.svd(B) 
>>> U

array([[-0.53753331+0.j        ,  0.84324252+0.j        ],
       [-0.84137487-0.05609166j, -0.53634276-0.03575618j]])

In [257]:
>>> M,N = B.shape 
>>> M

2

In [258]:
>>> Sig = linalg.diagsvd(s,M,N)
>>> Sig

array([[13.14973839,  0.        ,  0.        ],
       [ 0.        ,  2.66164991,  0.        ]])

In [259]:
>>> P,L,U = linalg.lu(C)
>>> P

array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])

In [260]:
>>> la, v = sparse.linalg.eigs(F,1) 
>>> la

array([9.13353098e-07-1.58198277e-06j])

In [261]:
v

array([[-1.00000000e+00-1.44490886e-12j],
       [-9.13353098e-07+1.58198277e-06j],
       [ 1.66844316e-12+2.88981773e-12j]])

In [262]:
sparse.linalg.svds(H, 2) 

(array([[ 0.0896289 ,  0.31199183],
        [-0.15103253,  0.32856498],
        [ 0.43716843,  0.33341805],
        [ 0.14360173,  0.36248592],
        [-0.05549292,  0.25373822],
        [-0.03837719,  0.25137952],
        [-0.13860157,  0.27088352],
        [ 0.29034478,  0.32158244],
        [-0.58404806,  0.26711999],
        [-0.4831576 ,  0.28353587],
        [ 0.27349952,  0.30988538]]),
 array([1.64266188, 3.39377227]),
 array([[ 0.10974959,  0.1872174 , -0.19746818, -0.27990214,  0.12578577,
         -0.03863405,  0.18542622, -0.00262108, -0.09610458,  0.07060299,
         -0.12885756, -0.00097423,  0.16494116,  0.04090348,  0.20487456,
         -0.17664681,  0.12465541,  0.0121042 ,  0.15644039, -0.00404202,
         -0.06446384,  0.03743109, -0.16738906, -0.08630791, -0.12037462,
          0.21916967, -0.15669527, -0.08530296, -0.00322768, -0.18582059,
          0.00329558, -0.03777782,  0.21218141,  0.15390769, -0.17794374,
         -0.16796521, -0.03530165, -0.09292841,  0