<span style="color:gray">Интеллектуальный анализ данных в R и Python. Семинар 1</span>

### Работа с данными в Python. Базовые операции Python 

---

Ниже приведено описание базовых операций Python.

##### 1. Выполнение базовых операций

<img src="python.PDF" width="800">

##### 2. Инициализация базовых библиотек

<img src="python_import_data.PDF" width="800">

---

<font color='green'>Задание для самостоятельной работы:</font>
    
1. Создать ячейку в данном Jupyter Notebook и повторить операции, приведенные в них разделах 1 и 2 выше.  
1. Загрузить результирующий .ipynb файл в папку /assignments/. Файлы должны именоваться как:<br>
   *'Seminar_1_' + surname*.

## Variables and Data Types

In [7]:
x=1

In [8]:
y=11

In [9]:
x+y

12

In [10]:
x+1

2

In [11]:
y-5

6

In [12]:
x*y

11

In [13]:
y**3

1331

In [14]:
x%10

1

In [15]:
y/float(5)

2.2

In [16]:
'-3','11.33',"String temp"

('-3', '11.33', 'String temp')

In [17]:
str(2.5)

'2.5'

In [18]:
str(True)

'True'

In [19]:
int('2')

2

In [20]:
int('-3')

-3

In [21]:
int(0xFF)

255

In [22]:
float('2.5')

2.5

In [23]:
float('1.0')

1.0

In [24]:
bool('True')

True

## Asking For Help

In [25]:
help(str)

Help on class str in module builtins:

class str(object)
 |  str(object='') -> str
 |  str(bytes_or_buffer[, encoding[, errors]]) -> str
 |  
 |  Create a new string object from the given object. If encoding or
 |  errors is specified, then the object must expose a data buffer
 |  that will be decoded using the given encoding and error handler.
 |  Otherwise, returns the result of object.__str__() (if defined)
 |  or repr(object).
 |  encoding defaults to sys.getdefaultencoding().
 |  errors defaults to 'strict'.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __format__(self, format_spec, /)
 |      Return a formatted version of the string as described by format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  

## Strings

In [26]:
s = '6chars'

In [27]:
s

'6chars'

In [28]:
s*2

'6chars6chars'

In [29]:
s + '+2'

'6chars+2'

In [30]:
'h' in s

True

## Lists

In [3]:
s1 = 'Ok'

In [4]:
s2 = 'NoProblem'

In [5]:
list1 = ['You', s1, 'I\'m', s2]

In [6]:
list2 = [[4,5,6,7], [3,4,5,6]]

In [7]:
list1

['You', 'Ok', "I'm", 'NoProblem']

In [8]:
list2

[[4, 5, 6, 7], [3, 4, 5, 6]]

In [9]:
list1[1]

'Ok'

In [10]:
list1[-3]

'Ok'

In [11]:
list1[1:3]

['Ok', "I'm"]

In [12]:
list1[1:]

['Ok', "I'm", 'NoProblem']

In [13]:
list1[:3]

['You', 'Ok', "I'm"]

In [14]:
list1[:]

['You', 'Ok', "I'm", 'NoProblem']

In [15]:
list2[1][0]

3

In [16]:
list2


[[4, 5, 6, 7], [3, 4, 5, 6]]

In [17]:
list2[1][:2]

[3, 4]

In [18]:
list1 + list1

['You', 'Ok', "I'm", 'NoProblem', 'You', 'Ok', "I'm", 'NoProblem']

In [19]:
list1 * 2

['You', 'Ok', "I'm", 'NoProblem', 'You', 'Ok', "I'm", 'NoProblem']

In [20]:
len(list2) > 4

False

In [21]:
>>> list1


['You', 'Ok', "I'm", 'NoProblem']

In [30]:
list1.index(s1)


0

In [31]:
list1.count(s1)


1

In [32]:
list1.append('!')

In [33]:
list1


['Ok', "I'm", 'NoProblem', '!']

In [34]:
list1.remove('!')

In [35]:
del(list1[0:1])


In [36]:
list1

["I'm", 'NoProblem']

In [37]:
list1.reverse()

In [38]:
list1

['NoProblem', "I'm"]

In [39]:
list1.extend('!')

In [40]:
list1

['NoProblem', "I'm", '!']

In [41]:
list1.pop(-1)

'!'

In [42]:
list1

['NoProblem', "I'm"]

In [43]:
list1.insert(0,'!')

In [44]:
list1

['!', 'NoProblem', "I'm"]

In [45]:
list1.sort()

In [46]:
list1

['!', "I'm", 'NoProblem']

## Strings

In [47]:
s2[3]

'r'

In [48]:
s2[1:3]

'oP'

In [49]:
s2


'NoProblem'

In [50]:
s2.upper()

'NOPROBLEM'

In [51]:
s2.lower()

'noproblem'

In [52]:
s1.count('\'')

0

In [53]:
s2.replace('', 'o')

'oNoooPoroooboloeomo'

In [54]:
s2.strip()

'NoProblem'

## Libraries

In [55]:
import numpy


In [56]:
import numpy as np

In [57]:
from math import pi

## Numpy Arrays

In [58]:
list1 = [1, 2, 3, 4]

In [59]:
arr = np.array(list1)

In [60]:
_2darr = np.array([[1,2,3],[4,5,6]])

In [61]:
arr

array([1, 2, 3, 4])

In [62]:
_2darr

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
arr[1]

2

In [64]:
arr[0:2]

array([1, 2])

In [65]:
_2darr[:,0]

array([1, 4])

In [66]:
_2darr > 3

array([[False, False, False],
       [ True,  True,  True]])

In [67]:
_2darr * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [68]:
arr + np.array([5, 6, 7, 8])

array([ 6,  8, 10, 12])

In [69]:
arr

array([1, 2, 3, 4])

In [70]:
arr.shape

(4,)

In [71]:
np.append(arr,1)

array([1, 2, 3, 4, 1])

In [72]:
np.insert(arr, 1, 5)

array([1, 5, 2, 3, 4])

In [73]:
np.delete(arr,[1])

array([1, 3, 4])

In [74]:
np.mean(arr)

2.5

In [75]:
arr

array([1, 2, 3, 4])

In [76]:
np.median(arr)

2.5

In [77]:
np.corrcoef(arr, arr)

array([[1., 1.],
       [1., 1.]])

In [78]:
np.std(arr)

1.118033988749895

## Importing Data in Python

In [79]:
import numpy as np

In [80]:
import pandas as pd

## Help

In [81]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


In [82]:
help(pd.read_csv)

Help on function read_csv in module pandas.io.parsers:

read_csv(filepath_or_buffer: Union[str, pathlib.Path, IO[~AnyStr]], sep=',', delimiter=None, header='infer', names=None, index_col=None, usecols=None, squeeze=False, prefix=None, mangle_dupe_cols=True, dtype=None, engine=None, converters=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, skipfooter=0, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=False, skip_blank_lines=True, parse_dates=False, infer_datetime_format=False, keep_date_col=False, date_parser=None, dayfirst=False, cache_dates=True, iterator=False, chunksize=None, compression='infer', thousands=None, decimal=b'.', lineterminator=None, quotechar='"', quoting=0, doublequote=True, escapechar=None, comment=None, encoding=None, dialect=None, error_bad_lines=True, warn_bad_lines=True, delim_whitespace=False, low_memory=True, memory_map=False, float_precision=None)
    Read a comma-separated values (csv) file into Dat

## Text Files

In [83]:
fname = 'man.txt'

In [84]:
file = open(fname, mode='r+')

In [85]:
text = file.read()

In [86]:
print(file.closed)

False


In [87]:
file.close()

In [88]:
print(text)

First guy, a, 1
Second guy, b, 2
Third guy, c, 3
4 guy, d, 4
5 guy, e, 5
6 guy, f, 6
7 guy, g, 7
8 guy, i, 8


In [89]:
file = open('man.txt', 'r+')
print(file.readline())
print(file.readline())
print(file.readline())

First guy, a, 1

Second guy, b, 2

Third guy, c, 3



In [90]:
fname = 'mans.txt'

In [91]:
>>> fname = 'man.txt'
>>> data = np.loadtxt(fname,
 delimiter=',',
 skiprows=2,
 usecols=[0,2],
 dtype=str)

print(data)

[['Third guy' ' 3']
 ['4 guy' ' 4']
 ['5 guy' ' 5']
 ['6 guy' ' 6']
 ['7 guy' ' 7']
 ['8 guy' ' 8']]


In [92]:
>>> fname = 'man.csv'
>>> data = np.genfromtxt(fname,  delimiter=',',
 names=True,
 dtype=None)

print(data)

[(b'Second guy', b' b', 2) (b'Third guy', b' c', 3) (b'4 guy', b' d', 4)
 (b'5 guy', b' e', 5) (b'6 guy', b' f', 6) (b'7 guy', b' g', 7)
 (b'8 guy', b' i', 8)]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  after removing the cwd from sys.path.


In [93]:
data_array = np.recfromcsv(fname)

/usr/lib/python3/dist-packages/numpy/lib/npyio.py:2315: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  output = genfromtxt(fname, **kwargs)


In [94]:
print(data_array)

[(b'Second guy', b' b', 2) (b'Third guy', b' c', 3) (b'4 guy', b' d', 4)
 (b'5 guy', b' e', 5) (b'6 guy', b' f', 6) (b'7 guy', b' g', 7)
 (b'8 guy', b' i', 8)]


In [95]:
>>> fname2 = 'man.csv'
>>> data2 = pd.read_csv(fname2,
 nrows=4, #Number of rows of file to read
 header=None, #Row number to use as col names 
 sep='\n', #Delimiter to use 
 comment='#', #Character to split comments
 na_values=[""]) 

In [96]:
print(data2)

                  0
0   First guy, a, 1
1  Second guy, b, 2
2   Third guy, c, 3
3       4 guy, d, 4


## Excel Spreadsheets

In [99]:
#fname = 'man.csv'
#>>> data = pd.ExcelFile(fname)
#>>> df_sheet1 = data.parse(0,
# parse_cols=[0],
# skiprows=[0],
# names=['Number'])
#print(df_sheet1)

XLRDError: Unsupported format, or corrupt file: Expected BOF record; found b'First gu'

In [98]:
#>>> data.sheet_names


AttributeError: 'numpy.ndarray' object has no attribute 'sheet_names'

## SAS Files

In [100]:
>>> from sas7bdat import SAS7BDAT
>>> with SAS7BDAT('urbanpop.sas7bdat') as file:
    df_sas = file.to_data_frame()

ModuleNotFoundError: No module named 'sas7bdat'

## Stata Files

In [189]:
>>> data = pd.read_stata('urbanpop.dta')

FileNotFoundError: [Errno 2] No such file or directory: 'urbanpop.dta'

## Relational Databases

In [190]:
>>> from sqlalchemy import create_engine
>>> engine = create_engine('sqlite://Northwind.sqlite')

ModuleNotFoundError: No module named 'sqlalchemy'

In [191]:
>>> table_names = engine.table_names()

NameError: name 'engine' is not defined

In [179]:
>>> con = engine.connect()
>>> rs = con.execute("SELECT * FROM Orders")
>>> df = pd.DataFrame(rs.fetchall())
>>> df.columns = rs.keys()
>>> con.close()

NameError: name 'engine' is not defined

In [180]:
>>> with engine.connect() as con:
rs = con.execute("SELECT OrderID FROM Orders")
df = pd.DataFrame(rs.fetchmany(size=5))
df.columns = rs.keys()

IndentationError: expected an indented block (<ipython-input-180-47459139b421>, line 2)

In [181]:
>>> df = pd.read_sql_query("SELECT * FROM Orders", engine)

NameError: name 'engine' is not defined

## Exploring Your Data

In [182]:
>>> data_array.dtype #Data type of array elements
>>> data_array.shape #Array dimensions
>>> len(data_array) 

2

In [183]:
>>> df.head() #Return first DataFrame rows
>>> df.tail() #Return last DataFrame rows
>>> df.index #Describe index
>>> df.columns #Describe DataFrame columns
>>> df.info() #Info on DataFrame
>>> data_array = data.values 

NameError: name 'df' is not defined

## Pickled Files

In [184]:
>>> import pickle
>>> with open('pickled_fruit.pkl', 'rb') as file:
    pickled_data = pickle.load(file)

FileNotFoundError: [Errno 2] No such file or directory: 'pickled_fruit.pkl'

## HDF5 Files

In [185]:
>>> import h5py
>>> filename = 'H-H1_LOSC_4_v1-815411200-4096.hdf5'
>>> data = h5py.File(filename, 'r')

OSError: Unable to open file (unable to open file: name = 'H-H1_LOSC_4_v1-815411200-4096.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

## Matlab Files

In [ ]:
>>> import scipy.io
>>> filename = 'workspace.mat'
>>> mat = scipy.io.loadmat(filename)

## Exploring Dictionarles

In [186]:
>>> print(mat.keys()) #Print dictionary keys
>>> for key in data.keys(): #Print dictionary keys
    print(key)

NameError: name 'mat' is not defined

In [187]:
>>> pickled_data.values() #Return dictionary values
>>> print(mat.items()) 

NameError: name 'pickled_data' is not defined

In [188]:
>>> for key in data ['meta'].keys()
print(key)

SyntaxError: invalid syntax (<ipython-input-188-c8d3efc34e38>, line 1)

In [189]:
>>> print(data['meta']['Description'].value)

TypeError: 'ExcelFile' object is not subscriptable

## Navigating Your File System

In [190]:
%ls
%cd
%pwd

 ’®¬ ў гбва®©б⢥ C ­Ґ Ё¬ҐҐв ¬ҐвЄЁ.
 ‘ҐаЁ©­л© ­®¬Ґа ⮬ : 1634-BD8D

 ‘®¤Ґа¦Ё¬®Ґ Ї ЇЄЁ C:\Users\hugod\Desktop\Љ“‹€ЉЋ‚‘ЉЂџ Ѓ€’‚Ђ\‹Ґе \labs

09.12.2019  00:23    <DIR>          .
09.12.2019  00:23    <DIR>          ..
09.12.2019  00:10    <DIR>          .ipynb_checkpoints
09.12.2019  00:17                19 excomunicado.csv
09.12.2019  00:18                23 excomunicado2.csv
09.12.2019  00:11    <DIR>          labs
09.12.2019  00:11         2я544я076 labs.7z
09.12.2019  00:13                17 man.txt
09.12.2019  00:14                36 mans.txt
24.09.2019  14:14           217я418 python.pdf
24.09.2019  14:14           138я489 python_import_data.pdf
09.12.2019  00:20             9я534 rockprivet.xlsx
09.12.2019  00:07             3я648 Seminar_0_Elfimov.ipynb
09.12.2019  00:02             1я633 Seminar_0_Elfimov.md
09.12.2019  00:07             1я753 Seminar_0_Elfimov.Rmd
09.12.2019  00:22           139я345 Seminar_1_Elfimov.ipynb
01.12.2019  09:15            80я189 Seminar_2_Elfimov.i

'C:\\Users\\hugod'

In [2]:
>>> import os
>>> path = "usr/tmp"

In [5]:
>>> wd = os.getcwd() #Store the name of current directory in a string

In [6]:
>>> os.listdir(wd) #Output contents of the directory in a list

['drive-download-20191210T054247Z-001.zip',
 'Seminar_3.ipynb',
 'Jupyter_notebook.pdf',
 'Seminar_1_Sagitov.ipynb',
 'rmarkdown-cheatsheet-1.pdf',
 'Seminar_2.ipynb',
 'Lecture_2_Sagitov.ipynb',
 'Lecture_0_Sagitov.txt',
 'Seminar_0_Sagitov.ipynb',
 '.ipynb_checkpoints',
 'Seminar_0_Romanov.md',
 'man.txt',
 'Seminar_0.ipynb',
 'Seminar_5.ipynb',
 'Lecture_5_Sagitov.ipynb',
 'Seminar_1.ipynb',
 'rmarkdown-cheatsheet-2.pdf',
 'markdown-2.pdf',
 'Lecture_6_Sagitov.ipynb',
 'Lecture_3_Sagitov.ipynb',
 'Jupyter_lab-1.pdf',
 'Seminar_4.ipynb',
 'Lecture_4_Sagitov.ipynb',
 'Jupyter_lab-2.pdf',
 'Seminar_0_Sagitov.Rmd',
 'rmarkdown-cheatsheet-2.0-1.pdf',
 'Untitled.ipynb',
 'Untitled1.ipynb',
 'Lecture_0.ipynb',
 'Lecture_1_Sagitov.ipynb']

In [194]:
>>> os.chdir(path) #Change current working directory

FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: 'usr/tmp'

In [195]:
>>> os.rename("test1.txt", #Rename a file
 "test2.txt")

FileNotFoundError: [WinError 2] Не удается найти указанный файл: 'test1.txt' -> 'test2.txt'

In [196]:
>>> os.remove("test3.txt") #Delete an existing file 

FileNotFoundError: [WinError 2] Не удается найти указанный файл: 'test3.txt'

In [197]:
>>> os.mkdir("newdir")